name: test

on:
  push:
    branches:
      - 'main'
      - 'staging'
  pull_request:
    branches:
      - 'main'
      - 'staging'

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: use node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys:
            ${{ runner.OS }}-build-${{ env.cache-name }}
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint
